title: Dr. ABOUABDALLAH M. Anwar
logo: "/images/cv-phot.jpeg?raw=true" # your photo (or logo) here
description: >ğŸ‘‹I'm PHD in Applied MAthematics / Cloud Data Scientist with 2 years of experiences 
  <br><br>
- ğŸ‘€ Iâ€™m interested in ML/MLOps and Data engineering
- ğŸŒ± Iâ€™m currently Data Scientist/Cloud engineer
- ğŸ’ï¸ Iâ€™m looking to collaborate on ML and create team for Kaggle competitions.
- ğŸ“« How to reach me : https://www.linkedin.com/in/anwarabouabdallah/
- I have 2 aws certification and preparing my first azure certification https://www.credly.com/users/mohamed_anwar_abouabdallah/badges
 
More details :

My name is Anwar and this world, I'm out of it 

'Cause with all this \alpha - \beta -\gamma shit, I'm startin' to sound like A Math-ALF a bit

Ha ha, It kill me, this technologie and climate change's counterfeit

I was mislead by the sound of it, how am I gonna get turnt up on this coffee a little bit? (Yeah)



Checked that hyperparameters in a model but where hidden 

Ciga coffe, then chill and try to find my problems

Living more than quarter century caused me to feel like I'm going bonkers

For real, think my neural network just born and grown and now start talkin'

I spilled like, severals years increasin' my it, math and data skills

Think my neural networks is startin' to feel like a spoiled carton of milk

theme: jekyll-theme-minimal
  
